# Generated by Django 5.1.1 on 2025-12-07 13:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='Proje Başlığı')),
                ('description', models.TextField(verbose_name='Açıklama')),
                ('image', models.ImageField(upload_to='projects/', verbose_name='Proje Görseli')),
                ('tech_stack', models.CharField(max_length=200, verbose_name='Teknolojiler')),
                ('github_link', models.URLField(blank=True, null=True, verbose_name='GitHub Linki')),
                ('live_link', models.URLField(blank=True, null=True, verbose_name='Canlı Demo Linki')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
