# Generated by Django 5.1.3 on 2025-12-25 19:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0003_experience'),
    ]

    operations = [
        migrations.AddField(
            model_name='experience',
            name='category',
            field=models.CharField(choices=[('work', 'Work Experience'), ('education', 'Education'), ('certificate', 'Certificate')], default='work', max_length=20),
        ),
    ]
