# Generated by Django 5.1.3 on 2025-12-25 21:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0004_experience_category'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='experience',
            options={'ordering': [models.OrderBy(models.F('end_date'), descending=True, nulls_first=True), '-start_date']},
        ),
        migrations.AddField(
            model_name='experience',
            name='description_tr',
            field=models.TextField(blank=True, null=True, verbose_name='Açıklama (Türkçe)'),
        ),
        migrations.AddField(
            model_name='project',
            name='description_tr',
            field=models.TextField(blank=True, null=True, verbose_name='Açıklama (Türkçe)'),
        ),
        migrations.AlterField(
            model_name='experience',
            name='description',
            field=models.TextField(blank=True, help_text='English Description'),
        ),
        migrations.AlterField(
            model_name='project',
            name='description',
            field=models.TextField(blank=True, help_text='English Description'),
        ),
    ]
