# Generated by Django 5.1.3 on 2026-01-02 20:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0006_contactmessage'),
    ]

    operations = [
        migrations.AddField(
            model_name='experience',
            name='title_tr',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Başlık (Türkçe)'),
        ),
        migrations.AddField(
            model_name='project',
            name='title_tr',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Başlık (Türkçe)'),
        ),
    ]
