import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { LanguageProvider } from '@/context/LanguageContext';
import {Inter} from 'next/font/google';
import LanguageToggle from '@/components/navigation/LanguageToggle';
import ScrollProgress from '@/components/ui/ScrollProgress';
import ScrollToTop from "@/components/ui/ScrollToTop";
import HomeLink from '@/components/navigation/HomeLink';
import { dictionary } from '@/lib/dictionary';

const inter = Inter({
  subsets: ['latin'],
  variable: '--font-inter',
});

const t = dictionary.en;

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Mertcan | Portfolio",
  description: "Generated by create next app",
  //metadataBase: new URL('https://mertcanercan.com'),
  metadataBase : new URL('http://127.0.0.1:3000/'),
  openGraph: {
      title: 'Mertcan Ercan | Portfolio',
      description: t.blog.description,
      url: 'https://mertcanercan.com',
      siteName: 'Mertcan Ercan Portfolio',
      locale: 'tr_TR',
      type: 'website',
      images: [
        {
          url: '/icon.jpg',
          width: 1200,
          height: 630,
          alt: 'Mertcan Ercan - Portfolio Cover',
        },
      ],
    },

  twitter: {
    card: 'summary_large_image',
    title: 'Mertcan Ercan | Global Traveller & Tech Enthusiast',
    description: t.blog.description,
    images: ['/icon.jpg'],
  },

  icons: {
    icon: '/icon.jpg',
    shortcut: '/icon.jpg',
    apple: '/apple-icon.png',
  },
};



export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        suppressHydrationWarning={true}
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <ScrollProgress />

        <LanguageProvider>
          <HomeLink />
          <LanguageToggle />
          {children}
        </LanguageProvider>
        <ScrollToTop/>
      </body>
    </html>
  );
}
