# Generated by Django 5.1.3 on 2025-12-29 19:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_category_name_tr_post_content_tr_post_location_tr_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='category_tr',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='posts_tr', to='blog.category'),
        ),
    ]
