# Generated by Django 5.1.3 on 2025-12-29 19:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_post_category_tr'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='category_tr',
        ),
    ]
