# Generated by Django 5.1.3 on 2026-01-04 13:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0009_post_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='preview_image',
            field=models.FileField(blank=True, help_text='If provided, this image will be used as a preview for the blog post.', null=True, upload_to='blog/previews/'),
        ),
    ]
