# Generated by Django 5.1.3 on 2026-01-08 20:13

import cloudinary_storage.storage
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0010_post_preview_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='preview_image',
            field=models.FileField(blank=True, help_text='If provided, this image will be used as a preview for the blog post.', null=True, storage=cloudinary_storage.storage.RawMediaCloudinaryStorage(), upload_to='blog/previews/'),
        ),
    ]
